heat_template_version: 2015-04-30
description: Web server
parameters:
  image:
    type: string
    description: Image used for servers
  key_name:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the servers
  pool_id:
    type: string
    description: Pool to contact
  metadata:
    type: json
  network:
    type: string
    description: Network used by the server
  external_network_id:
    type: string
    description: External Network
    default: 73a32a5d-8a0b-4ffc-9c32-a288224917ac
  user_data:
    type: string
    description: Server user_data
#  db_ip:
#    type: string
#    description: DB Server IP


resources:
  lamp_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: external_network_id}

  lamp:
    type: OS::Nova::Server
    properties:
      name: t1-web
      flavor: {get_param: flavor}
      image: t1-web-v3
      key_name: {get_param: key_name}
      metadata: {get_param: metadata}
      networks: [{network: {get_param: network} }]
      user_data: {get_param: user_data}
      user_data_format: RAW

  lamp_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: lamp_floating_ip }
      server_id: { get_resource: lamp }

  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [lamp, first_address]}
      protocol_port: 80
