heat_template_version: 2015-04-30
description: AutoScaling in LoadBalancer
parameters:
  image:
    type: string
    description: Image used for servers
    #default: d36f2c18-1fcd-4a65-a973-b465897e6b57 # lamp5
    default: LAMP5.4
  key:
    type: string
    description: SSH key to connect to the servers
    default: key1
  flavor:
    type: string
    description: flavor used by the web servers
    default: af7c9a19-9636-44f9-af05-e0479d6a15b0
  network:
    type: string
    description: Network used by the server
    default: a81ed667-4078-4095-a34c-65777ecbc68e
  subnet_id:
    type: string
    description: subnet on which the load balancer will be located
    default: f0ba0e25-c482-4e15-98f2-dc181dee2d79
  internal_subnet_cidr:
    type: string
    description: subnet IP/CIDR
    default: 10.0.0.0/24
  vm1_ip:
    label: "VM1 IP"
    type: string
    description: VM IP
    default: 10.0.0.101
  external_network_id:
    type: string
    description: UUID of a Neutron external network
    default: 73a32a5d-8a0b-4ffc-9c32-a288224917ac
  checkservice:
    type: string
    constraints:
      - allowed_values: [PING, TCP, HTTP, HTTPS]
    default: HTTP

resources:
  internal_net:
    type: 'OS::Neutron::Net'
    properties:
      name: "tenant1-internal-net"

  internal_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: "tenant1-internal-subnet"
      cidr: {get_param: internal_subnet_cidr}
      dns_nameservers: [8.8.8.8, 8.8.4.4]
      ip_version: 4
      network_id: {get_resource: internal_net}

  internal_port:
    type: OS::Neutron::Port
    properties:
      name: "tenant1-fixed-port"
      fixed_ips:
      - ip_address: {get_param: vm1_ip}
        subnet_id: {get_resource: internal_subnet}
      network_id: {get_resource: internal_net}

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: {network: external-network}

  bind_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: {get_resource: router}
      subnet_id: {get_resource: internal_subnet}

  asg:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      max_size: 3
      desired_capacity: 1
      resource:
        type: "http://192.168.121.102/as_server54.yaml"
        properties:
          flavor: {get_param: flavor}
          image: {get_param: image}
          key_name: {get_param: key}
          network: {get_resource: internal_net}
          pool_id: {get_resource: pool}
          metadata: {"metering.stack": {get_param: "OS::stack_id"}}

  web_server_scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 70
      scaling_adjustment: 1

  web_server_scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 30
      scaling_adjustment: -1

  cpu_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-up if the average CPU > 80% for 30 second
      meter_name: cpu_util
      statistic: avg
      period: 30
      evaluation_periods: 1
      threshold: 50
      alarm_actions:
        - {get_attr: [web_server_scaleup_policy, alarm_url]}
      matching_metadata: {'metadata.user_metadata.stack': {get_param: "OS::stack_id"}}
      comparison_operator: gt

  cpu_alarm_low:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-down if the average CPU < 15% for 30 second
      meter_name: cpu_util
      statistic: avg
      period: 30
      evaluation_periods: 1
      threshold: 15
      alarm_actions:
        - {get_attr: [web_server_scaledown_policy, alarm_url]}
      matching_metadata: {'metadata.user_metadata.stack': {get_param: "OS::stack_id"}}
      comparison_operator: lt

  monitor:
    type: OS::Neutron::HealthMonitor
    properties:
      type: {get_param: checkservice}
      delay: 5
      max_retries: 5
      timeout: 5

  pool:
    type: OS::Neutron::Pool
    properties:
      name: AutoScaling_Pool
      protocol: {get_param: checkservice}
      monitors: [{get_resource: monitor}]
      subnet_id: {get_resource: internal_subnet}
      lb_method: ROUND_ROBIN
      vip:
        protocol_port: 80
  lb:
    type: OS::Neutron::LoadBalancer
    properties:
      protocol_port: 80
      pool_id: {get_resource: pool}

  lb_floating:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: external_network_id}
      port_id: {get_attr: [pool, vip, port_id]}

outputs:
  scale_up_url:
    description: >
      This URL is the webhook to scale up the autoscaling group.  You
      can invoke the scale-up operation by doing an HTTP POST to this
      URL; no body nor extra headers are needed.
    value: {get_attr: [web_server_scaleup_policy, alarm_url]}
  scale_dn_url:
    description: >
      This URL is the webhook to scale down the autoscaling group.
      You can invoke the scale-down operation by doing an HTTP POST to
      this URL; no body nor extra headers are needed.
    value: {get_attr: [web_server_scaledown_policy, alarm_url]}
  pool_ip_address:
    value: {get_attr: [pool, vip, address]}
    description: The IP address of the load balancing pool
  #website_url:
    #value:
    #    str_replace:
    #    template: http://host/wordpress/
    #    params:
    #      #host: { get_attr: [lb_floating, floating_ip_address] }
    #description: >
    #  This URL is the "external" URL that can be used to access the
    #  Wordpress site.
  ceilometer_query:
    value:
      str_replace:
        template: >
          ceilometer statistics -m cpu_util
          -q metadata.user_metadata.stack=stackval -p 600 -a avg
        params:
          stackval: { get_param: "OS::stack_id" }
    description: >
      This is a Ceilometer query for statistics on the cpu_util meter
      Samples about OS::Nova::Server instances in this stack.  The -q
      parameter selects Samples according to the subject's metadata.
      When a VM's metadata includes an item of the form metering.X=Y,
      the corresponding Ceilometer resource has a metadata item of the
      form user_metadata.X=Y and samples about resources so tagged can
      be queried with a Ceilometer query term of the form
      metadata.user_metadata.X=Y.  In this case the nested stacks give
      their VMs metadata that is passed as a nested stack parameter,
      and this stack passes a metadata of the form metering.stack=Y,
      where Y is this stack's ID.
  